// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgUzgO-PHu9Pmy4xMfjSe7JOLHjWN9swM',
    appId: '1:77110948133:web:dd3d3fc3e3d9f3591a2acc',
    messagingSenderId: '77110948133',
    projectId: 'studenttask-164ff',
    authDomain: 'studenttask-164ff.firebaseapp.com',
    storageBucket: 'studenttask-164ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Sw5cCKjCtE-6V9G1hddvnNCwNtTbB20',
    appId: '1:77110948133:android:03426f81a17bc75e1a2acc',
    messagingSenderId: '77110948133',
    projectId: 'studenttask-164ff',
    storageBucket: 'studenttask-164ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB39kf_k5DJvUe46yRWv_10a7dw4dXwCH8',
    appId: '1:77110948133:ios:57864d98196dd0f31a2acc',
    messagingSenderId: '77110948133',
    projectId: 'studenttask-164ff',
    storageBucket: 'studenttask-164ff.firebasestorage.app',
    iosBundleId: 'com.example.studentAppTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB39kf_k5DJvUe46yRWv_10a7dw4dXwCH8',
    appId: '1:77110948133:ios:57864d98196dd0f31a2acc',
    messagingSenderId: '77110948133',
    projectId: 'studenttask-164ff',
    storageBucket: 'studenttask-164ff.firebasestorage.app',
    iosBundleId: 'com.example.studentAppTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgUzgO-PHu9Pmy4xMfjSe7JOLHjWN9swM',
    appId: '1:77110948133:web:31498a8b3efeaffe1a2acc',
    messagingSenderId: '77110948133',
    projectId: 'studenttask-164ff',
    authDomain: 'studenttask-164ff.firebaseapp.com',
    storageBucket: 'studenttask-164ff.firebasestorage.app',
  );
}
